
export enum ACCOUNT_TYPE {
  STUDENT = "STUDENT",
  OTHER = "OTHER",
}

export enum ACCOUNT_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum JOB_STATUS {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  ARCHIVE = "ARCHIVE",
}

export enum JOB_TYPES {
  FULLTIME = "FULLTIME",
  PARTTIME = "PARTTIME",
}